---
kind: Template
apiVersion: v1
metadata:
  name: grafana
  annotations:
    "openshift.io/display-name": Grafana
    description: |
      Grafana server with patched Prometheus datasource.
    iconClass: fa fa-cogs
    tags: "metrics,monitoring,grafana,prometheus"
parameters:
- description: The location of the grafana image
  name: IMAGE_GRAFANA
  value: mrsiano/grafana-ocp:latest
- description: The location of the proxy image
  name: IMAGE_PROXY
  value: openshift/oauth-proxy:v1.0.0
- description: External URL for the grafana route
  name: ROUTE_URL
  value: ""
objects:
- apiVersion: v1
  kind: Route
  metadata:
    name: grafana
    labels:
      app: grafana
  spec:
    host: "${ROUTE_URL}"
    to:
      kind: Service
      name: grafana
    port:
      targetPort: 3000
- apiVersion: v1
  kind: Service
  metadata:
    name: grafana
    labels:
      metrics-infra: grafana
      name: grafana
      app: grafana
  spec:
    ports:
    - name: grafana
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      app: grafana
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: grafana
    name: grafana
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: grafana
    template:
      metadata:
        labels:
          app: grafana
        name: grafana
      spec:
        serviceAccountName: grafana
        containers:
        - name: grafana
          image: ${IMAGE_GRAFANA}
          ports:
          - name: grafana-http
            containerPort: 3000
          volumeMounts:
          - mountPath: "/root/go/src/github.com/grafana/grafana/data"
            name: grafana-data
          - mountPath: "/root/go/src/github.com/grafana/grafana/conf"
            name: grafanaconfig
          command:
           - "./bin/grafana-server"
        volumes:
        - name: grafanaconfig
          configMap:
            name: grafana-config
        - emptyDir: {}
          name: grafana-data

